' Gambas module file

Public Sub GetGist(GistId As String) As String                                  'To 'Get' stuff from the web

  Dim hClient As HttpClient                                                     'To create a HTTP Client
  Dim sResult As String
  Dim vResult As Variant
  Dim sContent As String
  Dim vFile As Variant

  hClient = New HttpClient As "hClient"                                         'Create a HTTP Client
  With hClient                                                                  'With the Client..
    .URL = "https://api.github.com/gists/" & GistId                             'Set up the URL
    .Async = False                                                              'No Asynchronous transmission
    .TimeOut = 60                                                               'Don't hang around waiting for more than 60 seconds
    .get                                                                        'Get the data
  End With

  If Lof(hClient) Then sResult = Read #hClient, Lof(hClient)                    'When all the data is downloaded store it in sResult

  vResult = JSON.Decode(sResult, False)

  For Each vFile In vResult["files"]
    sContent = vFile["content"]
    Break
  Next

  Return sContent

End