' Gambas module file

Property Read Body As String
Private $sBuffer As String

Private Sub Decode()

  If Eof() Then Return
  While Not Eof()
    $sBuffer &= Read -4096
  Wend

End

Private Function Body_Read() As String

  Decode
  Return $sBuffer

End

Public Function ContainsParameter(sKey As String) As Boolean

  Dim Query As String
  Dim KeyValue As String[]

  For Each Query In Split(CGI!QUERY_STRING, "&")
    KeyValue = Split(Query, "=")
    If KeyValue.Max = 1 And If String.Comp(KeyValue[0], sKey, gb.IgnoreCase) = 0 Then
      Return True
    End If
  Next
  Return False

End

Public Function Parameter(sKey As String, Optional DefaultValue As String = "") As String

  Dim Query As String
  Dim KeyValue As String[]

  For Each Query In Split(CGI!QUERY_STRING, "&")
    KeyValue = Split(Query, "=")
    If KeyValue.Max = 1 And If String.Comp(KeyValue[0], sKey, gb.IgnoreCase) = 0 Then
      Return KeyValue[1]
    End If
  Next
  Return DefaultValue

End

Public Function IsParameter(sKey As String, DefaultValue As Boolean) As Boolean

  Return UCase(Parameter(sKey, DefaultValue)) Begins "T"

End
